---
title: "plotly_template: ToothGrowth"
author: "Powell Chu"
date: "1/24/2021"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ToothGrowth

A summary of the dataset *ToothGrowth* is as follows:
```{r ToothGrowth, echo=F, message=F, warning=F}
## ToothGrowth dataset
data("ToothGrowth")
library(plotly)
library(tidyr)
library(dplyr)
summary(ToothGrowth)
```

## Histogram 1

Histogram of the length of tooth growth based on the supplement.

```{r fig1, echo=F, warning=F}
fig1 <- plot_ly(ToothGrowth, alpha = 0.5, nbinsx = 20)
fig1 <- fig1 %>% layout(barmode="overlay", bargap=0.01)
fig1 <- fig1 %>% add_histogram(x = ~len, color = ~supp)
fig1
```

## Histogram 2

Histogram of the length of tooth growth based on the dosage level.

```{r fig2, echo=F, warning=F}
fig2 <- plot_ly(ToothGrowth, alpha = 0.5, nbinsx = 15)
fig2 <- fig2 %>% layout(barmode="overlay", bargap=0.01)
fig2 <- fig2 %>% add_histogram(x = ~len, color = ~as.factor(dose))
fig2
```

## Boxplot

Boxplot of the length of tooth growth from different dosage level and supplement.

```{r fig3, echo=F, warning=F}
fig3 <- plot_ly(ToothGrowth, x = ~as.factor(dose), y = ~len, 
                jitter = 0.3, pointpos = 0, boxpoints = 'all',
                color = ~supp, type = "box")
fig3 <- fig3 %>% layout(boxmode = "group")
fig3
```
