---
title       : ShinyApp_Iris
subtitle    : Coursera Data Products Project
author      : Powell Chu
date        : January/24/2021
output      : html_document #slidy_presentation
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow
runtime     : shiny
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Iris Dataset Histogram

```{r histogram, warning = F, echo=F}
shinyAppDir(
  "D:/Dropbox/Learning_programming/Coursera/Course4_Data_Products/Page2",
  options = list(
    width = "100%", height = 550
  )
)
```

## Model1: Linear Model

```{r lm1, warning = F, echo=F}
shinyAppDir(
  "D:/Dropbox/Learning_programming/Coursera/Course4_Data_Products/Page3",
  options = list(
    width = "100%", height = 550
  )
)
```

## Model2: Linear Model (with Brushing)

```{r lm2, warning = F, echo=F}
shinyAppDir(
  "D:/Dropbox/Learning_programming/Coursera/Course4_Data_Products/Page4",
  options = list(
    width = "100%", height = 550
  )
)
```

## Model3: Kmeans Clustering

```{r kmeanscluster, warning = F, echo=F}
shinyAppDir(
  "D:/Dropbox/Learning_programming/Coursera/Course4_Data_Products/Page5",
  options = list(
    width = "100%", height = 550
  )
)
```





